# Generated by Django 2.2 on 2019-04-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=20)),
                ('parent_token', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('closing_price', models.CharField(max_length=20)),
                ('expiry', models.CharField(max_length=20)),
                ('strike_price', models.CharField(max_length=20)),
                ('tick_size', models.CharField(max_length=20)),
                ('lot_size', models.CharField(max_length=20)),
                ('instrument_type', models.CharField(max_length=20)),
                ('isin', models.CharField(max_length=20)),
            ],
        ),
    ]
