# Generated by Django 2.2.2 on 2019-07-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='full_quote',
            name='ask',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='full_quote',
            name='bid',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
