# Generated by Django 2.2 on 2019-04-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='closing_price',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='exchange',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='expiry',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='isin',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='lot_size',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='parent_token',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='strike_price',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='symbol',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='tick_size',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='token',
            field=models.CharField(max_length=40),
        ),
    ]
