# Generated by Django 2.1.7 on 2019-05-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190416_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Full_Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=40)),
                ('symbol', models.CharField(max_length=40)),
                ('ltp', models.CharField(max_length=40)),
                ('close', models.CharField(max_length=40)),
                ('open', models.CharField(max_length=40)),
                ('high', models.CharField(max_length=40)),
                ('low', models.CharField(max_length=40)),
                ('vtt', models.CharField(max_length=40)),
                ('atp', models.CharField(max_length=40)),
                ('oi', models.CharField(max_length=40)),
                ('spot_price', models.CharField(max_length=40)),
                ('total_buy_qty', models.CharField(max_length=40)),
                ('total_sell_qty', models.CharField(max_length=40)),
                ('lower_circuit', models.CharField(max_length=40)),
                ('upper_circuit', models.CharField(max_length=40)),
                ('yearly_low', models.CharField(max_length=40)),
                ('yearly_high', models.CharField(max_length=40)),
                ('ltt', models.CharField(max_length=40)),
            ],
        ),
    ]
