# Generated by Django 2.1.7 on 2019-05-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_full_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='full_quote',
            name='strike_price',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
