# Generated by Django 2.2.2 on 2019-08-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option_Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_symbol', models.CharField(max_length=40)),
                ('strike_price', models.FloatField(max_length=40)),
                ('put_symbol', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
