# Generated by Django 2.1.7 on 2019-05-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_full_quote_strike_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full_quote',
            name='strike_price',
            field=models.FloatField(max_length=40),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='strike_price',
            field=models.FloatField(max_length=40),
        ),
    ]
