# Generated by Django 2.1.7 on 2019-05-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190512_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='strike_price',
            field=models.FloatField(max_length=40),
        ),
    ]
