# Generated by Django 2.1.7 on 2019-05-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190512_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full_quote',
            name='oi',
            field=models.FloatField(max_length=40),
        ),
    ]
