# Generated by Django 2.1.7 on 2019-06-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190512_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expiry_Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upstox_date', models.FloatField(max_length=40)),
                ('expiry_date', models.FloatField(max_length=40)),
            ],
        ),
    ]
