# Generated by Django 2.1.7 on 2019-06-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiry_date',
            name='expiry_date',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='expiry_date',
            name='upstox_date',
            field=models.CharField(max_length=40),
        ),
    ]
