# Generated by Django 2.1.7 on 2019-06-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190615_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiry_date',
            name='label_date',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
