# Generated by Django 2.1.7 on 2019-06-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_expiry_date_label_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiry_date',
            name='future_date',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
